export const fillerReports = [
  {
    id: "1",
    additionalInfo: "Very friendly and loves treats",
    breed: "Golden Retriever",
    customBreed: "",
    dateLastSeen: "2026-03-10",
    email: "johnsmith1@gmail.com",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
    ownerName: "John Smith",
    petName: "Buddy",
    petType: "dog",
    phone: "555-123-4567",
    userId: "user_001"
  },
  {
    id: "2",
    additionalInfo: "Shy, may hide under cars",
    breed: "Siamese",
    customBreed: "",
    dateLastSeen: "2026-03-12",
    email: "emilyjones@gmail.com",
    image: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
    ownerName: "Emily Jones",
    petName: "Luna",
    petType: "cat",
    phone: "555-234-5678",
    userId: "user_002"
  },
  {
    id: "3",
    additionalInfo: "Has a red collar with tag",
    breed: "German Shepherd",
    customBreed: "",
    dateLastSeen: "2026-03-08",
    email: "mikebrown@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Mike Brown",
    petName: "Max",
    petType: "dog",
    phone: "555-345-6789",
    userId: "user_003"
  },
  {
    id: "4",
    additionalInfo: "Very fluffy, responds to name",
    breed: "",
    customBreed: "Persian Mix",
    dateLastSeen: "2026-03-15",
    email: "sarahlee@gmail.com",
    image: "https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    ownerName: "Sarah Lee",
    petName: "Snowball",
    petType: "cat",
    phone: "555-456-7890",
    userId: "user_004"
  },
  {
    id: "5",
    additionalInfo: "Limping slightly on left leg",
    breed: "Bulldog",
    customBreed: "",
    dateLastSeen: "2026-03-18",
    email: "davidwilson@gmail.com",
    image: "https://images.dog.ceo/breeds/bulldog-english/jager-2.jpg",
    ownerName: "David Wilson",
    petName: "Rocky",
    petType: "dog",
    phone: "555-567-8901",
    userId: "user_005"
  },
  {
    id: "6",
    additionalInfo: "Green eyes, very vocal",
    breed: "Maine Coon",
    customBreed: "",
    dateLastSeen: "2026-03-20",
    email: "oliviawhite@gmail.com",
    image: "./animalImgs/cat.webp",
    ownerName: "Olivia White",
    petName: "Leo",
    petType: "cat",
    phone: "555-678-9012",
    userId: "user_006"
  },
  {
    id: "7",
    additionalInfo: "Wearing a blue harness",
    breed: "",
    customBreed: "Labradoodle",
    dateLastSeen: "2026-03-22",
    email: "chrisgreen@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Chris Green",
    petName: "Charlie",
    petType: "dog",
    phone: "555-789-0123",
    userId: "user_007"
  },
  {
    id: "8",
    additionalInfo: "Very small, may be scared",
    breed: "Chihuahua",
    customBreed: "",
    dateLastSeen: "2026-03-19",
    email: "lauramartin@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Laura Martin",
    petName: "Bella",
    petType: "dog",
    phone: "555-890-1234",
    userId: "user_008"
  },
  {
    id: "9",
    additionalInfo: "Very friendly and loves treats",
    breed: "Golden Retriever",
    customBreed: "",
    dateLastSeen: "2026-03-10",
    email: "johnsmith1@gmail.com",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
    ownerName: "John Smith",
    petName: "Buddy",
    petType: "dog",
    phone: "555-123-4567",
    userId: "user_001"
  },
  {
    id: "10",
    additionalInfo: "Shy, may hide under cars",
    breed: "Siamese",
    customBreed: "",
    dateLastSeen: "2026-03-12",
    email: "emilyjones@gmail.com",
    image: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
    ownerName: "Emily Jones",
    petName: "Luna",
    petType: "cat",
    phone: "555-234-5678",
    userId: "user_002"
  },
  {
    id: "11",
    additionalInfo: "Has a red collar with tag",
    breed: "German Shepherd",
    customBreed: "",
    dateLastSeen: "2026-03-08",
    email: "mikebrown@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Mike Brown",
    petName: "Max",
    petType: "dog",
    phone: "555-345-6789",
    userId: "user_003"
  },
  {
    id: "12",
    additionalInfo: "Very fluffy, responds to name",
    breed: "",
    customBreed: "Persian Mix",
    dateLastSeen: "2026-03-15",
    email: "sarahlee@gmail.com",
    image: "https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    ownerName: "Sarah Lee",
    petName: "Snowball",
    petType: "cat",
    phone: "555-456-7890",
    userId: "user_004"
  },
  {
    id: "13",
    additionalInfo: "Limping slightly on left leg",
    breed: "Bulldog",
    customBreed: "",
    dateLastSeen: "2026-03-18",
    email: "davidwilson@gmail.com",
    image: "https://images.dog.ceo/breeds/bulldog-english/jager-2.jpg",
    ownerName: "David Wilson",
    petName: "Rocky",
    petType: "dog",
    phone: "555-567-8901",
    userId: "user_005"
  },
  {
    id: "14",
    additionalInfo: "Green eyes, very vocal",
    breed: "Maine Coon",
    customBreed: "",
    dateLastSeen: "2026-03-20",
    email: "oliviawhite@gmail.com",
    image: "./animalImgs/cat.webp",
    ownerName: "Olivia White",
    petName: "Leo",
    petType: "cat",
    phone: "555-678-9012",
    userId: "user_006"
  },
  {
    id: "15",
    additionalInfo: "Wearing a blue harness",
    breed: "",
    customBreed: "Labradoodle",
    dateLastSeen: "2026-03-22",
    email: "chrisgreen@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Chris Green",
    petName: "Charlie",
    petType: "dog",
    phone: "555-789-0123",
    userId: "user_007"
  },
  {
    id: "16",
    additionalInfo: "Very small, may be scared",
    breed: "Chihuahua",
    customBreed: "",
    dateLastSeen: "2026-03-19",
    email: "lauramartin@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Laura Martin",
    petName: "Bella",
    petType: "dog",
    phone: "555-890-1234",
    userId: "user_008"
  },
  {
    id: "17",
    additionalInfo: "Very friendly and loves treats",
    breed: "Golden Retriever",
    customBreed: "",
    dateLastSeen: "2026-03-10",
    email: "johnsmith1@gmail.com",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
    ownerName: "John Smith",
    petName: "Buddy",
    petType: "dog",
    phone: "555-123-4567",
    userId: "user_001"
  },
  {
    id: "18",
    additionalInfo: "Shy, may hide under cars",
    breed: "Siamese",
    customBreed: "",
    dateLastSeen: "2026-03-12",
    email: "emilyjones@gmail.com",
    image: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
    ownerName: "Emily Jones",
    petName: "Luna",
    petType: "cat",
    phone: "555-234-5678",
    userId: "user_002"
  },
  {
    id: "19",
    additionalInfo: "Has a red collar with tag",
    breed: "German Shepherd",
    customBreed: "",
    dateLastSeen: "2026-03-08",
    email: "mikebrown@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Mike Brown",
    petName: "Max",
    petType: "dog",
    phone: "555-345-6789",
    userId: "user_003"
  },
  {
    id: "20",
    additionalInfo: "Very fluffy, responds to name",
    breed: "",
    customBreed: "Persian Mix",
    dateLastSeen: "2026-03-15",
    email: "sarahlee@gmail.com",
    image: "https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    ownerName: "Sarah Lee",
    petName: "Snowball",
    petType: "cat",
    phone: "555-456-7890",
    userId: "user_004"
  },
  {
    id: "21",
    additionalInfo: "Limping slightly on left leg",
    breed: "Bulldog",
    customBreed: "",
    dateLastSeen: "2026-03-18",
    email: "davidwilson@gmail.com",
    image: "https://images.dog.ceo/breeds/bulldog-english/jager-2.jpg",
    ownerName: "David Wilson",
    petName: "Rocky",
    petType: "dog",
    phone: "555-567-8901",
    userId: "user_005"
  },
  {
    id: "22",
    additionalInfo: "Green eyes, very vocal",
    breed: "Maine Coon",
    customBreed: "",
    dateLastSeen: "2026-03-20",
    email: "oliviawhite@gmail.com",
    image: "./animalImgs/cat.webp",
    ownerName: "Olivia White",
    petName: "Leo",
    petType: "cat",
    phone: "555-678-9012",
    userId: "user_006"
  },
  {
    id: "23",
    additionalInfo: "Wearing a blue harness",
    breed: "",
    customBreed: "Labradoodle",
    dateLastSeen: "2026-03-22",
    email: "chrisgreen@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Chris Green",
    petName: "Charlie",
    petType: "dog",
    phone: "555-789-0123",
    userId: "user_007"
  },
  {
    id: "24",
    additionalInfo: "Very small, may be scared",
    breed: "Chihuahua",
    customBreed: "",
    dateLastSeen: "2026-03-19",
    email: "lauramartin@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Laura Martin",
    petName: "Bella",
    petType: "dog",
    phone: "555-890-1234",
    userId: "user_008"
  },
  {
    id: "25",
    additionalInfo: "Very friendly and loves treats",
    breed: "Golden Retriever",
    customBreed: "",
    dateLastSeen: "2026-03-10",
    email: "johnsmith1@gmail.com",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
    ownerName: "John Smith",
    petName: "Buddy",
    petType: "dog",
    phone: "555-123-4567",
    userId: "user_001"
  },
  {
    id: "26",
    additionalInfo: "Shy, may hide under cars",
    breed: "Siamese",
    customBreed: "",
    dateLastSeen: "2026-03-12",
    email: "emilyjones@gmail.com",
    image: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
    ownerName: "Emily Jones",
    petName: "Luna",
    petType: "cat",
    phone: "555-234-5678",
    userId: "user_002"
  },
  {
    id: "27",
    additionalInfo: "Has a red collar with tag",
    breed: "German Shepherd",
    customBreed: "",
    dateLastSeen: "2026-03-08",
    email: "mikebrown@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Mike Brown",
    petName: "Max",
    petType: "dog",
    phone: "555-345-6789",
    userId: "user_003"
  },
  {
    id: "28",
    additionalInfo: "Very fluffy, responds to name",
    breed: "",
    customBreed: "Persian Mix",
    dateLastSeen: "2026-03-15",
    email: "sarahlee@gmail.com",
    image: "https://cdn2.thecatapi.com/images/MTY3ODIyMQ.jpg",
    ownerName: "Sarah Lee",
    petName: "Snowball",
    petType: "cat",
    phone: "555-456-7890",
    userId: "user_004"
  },
  {
    id: "29",
    additionalInfo: "Limping slightly on left leg",
    breed: "Bulldog",
    customBreed: "",
    dateLastSeen: "2026-03-18",
    email: "davidwilson@gmail.com",
    image: "https://images.dog.ceo/breeds/bulldog-english/jager-2.jpg",
    ownerName: "David Wilson",
    petName: "Rocky",
    petType: "dog",
    phone: "555-567-8901",
    userId: "user_005"
  },
  {
    id: "30",
    additionalInfo: "Green eyes, very vocal",
    breed: "Maine Coon",
    customBreed: "",
    dateLastSeen: "2026-03-20",
    email: "oliviawhite@gmail.com",
    image: "./animalImgs/cat.webp",
    ownerName: "Olivia White",
    petName: "Leo",
    petType: "cat",
    phone: "555-678-9012",
    userId: "user_006"
  },
  {
    id: "31",
    additionalInfo: "Wearing a blue harness",
    breed: "",
    customBreed: "Labradoodle",
    dateLastSeen: "2026-03-22",
    email: "chrisgreen@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Chris Green",
    petName: "Charlie",
    petType: "dog",
    phone: "555-789-0123",
    userId: "user_007"
  },
  {
    id: "32",
    additionalInfo: "Very small, may be scared",
    breed: "Chihuahua",
    customBreed: "",
    dateLastSeen: "2026-03-19",
    email: "lauramartin@gmail.com",
    image: "./animalImgs/pomeranian.webp",
    ownerName: "Laura Martin",
    petName: "Bella",
    petType: "dog",
    phone: "555-890-1234",
    userId: "user_008"
  },
  {
    id: "33",
    additionalInfo: "Very friendly and loves treats",
    breed: "Golden Retriever",
    customBreed: "",
    dateLastSeen: "2026-03-10",
    email: "johnsmith1@gmail.com",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
    ownerName: "John Smith",
    petName: "Buddy",
    petType: "dog",
    phone: "555-123-4567",
    userId: "user_001"
  },
];
